### PR TITLE
DO NO MERGE: Remove web/modules/contrib which are install by composer

### PR DESCRIPTION
**Pull request by longhotsummer**
Once this is merged, I will bring composer.lock up to date with `composer install`.

@roger-cts I thought I had removed all the 3rd party code, but apparently not.

### CODE REVIEW

**Comment by roger-cts** [comment]
I don't think we can ignore the entire modules/contrib as the settings.yml will hold settings for certain modules.

**Comment by longhotsummer** [comment]
Good point. Let me double check if any of them have changed from what composer installs.

**Comment by longhotsummer** [comment]
I'm holding off on this until Roger's PR is done.

**Comment by longhotsummer** [comment]
Re-doing this PR after big updates to the master branch.

I don't see any settings.yml files in web/modules/contrib so I think it's safe to remove this. Any non-default settings.yml file will need to be added explicitly.

**Comment by longhotsummer** [comment]
Correcting, there are `foo.settings.yml` files, but none of them are different to the defaults.

**Pull request closed without merging**
