### PR TITLE
189 patch node error logic exception

### PR DESCRIPTION
**Pull request by cristiroma**
We have debugged and fixed the issue. The filefield_paths module is leaking metadata (calls ->render() in the API context) as reported on https://www.drupal.org/project/filefield_paths/issues/3074642.

Patching the bug fixes the test we've written. I cannot assess though how  it interacts with `s3://` stuff. Can you try?

The debugging was done based on this article: https://www.lullabot.com/articles/early-rendering-a-lesson-in-debugging-drupal-8 which describes a similar problem.

### CODE REVIEW

**Comment by cristiroma** [comment]
Not sure why travis is failing, maybe we can have a look @longhotsummer? On my local all the tests are passing

```
cristiroma@prometheus:~/Work/laws.africa/liiweb$ ./vendor/bin/phpunit --group liiweb
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Testing 
......                                                              6 / 6 (100%)

Time: 1.65 minutes, Memory: 8.00 MB

OK (6 tests, 78 assertions)

```

**Comment by longhotsummer** [comment]
Thanks @cristiroma -- I'm not sure why tests are failing, I don't know enough about Drupal. Perhaps it's a dependency version issue?

**Comment by longhotsummer** [comment]
The fact that other builds are passing definitely points to something in this commit.

Are all the config changes necessary -- perhaps just focus on the patch file and see if that works?

**Comment by longhotsummer** [comment]
@Hayk-web Cristian has suggested this as a cleaner fix for #189. The tests work on his system. Would you be able to take a look and see if you can determine why the tests are failing?

Thanks!

**Comment by Hayk-web** [comment]
Hello everyone. I am starting to work on this task.

**Comment by Hayk-web** [comment]
Please, could you provide information about the applied patch. It includes logic related to paths and fields, the second part is about bubbled cacheability metadata. For which case have you used the patch(https://www.drupal.org/files/issues/2019-08-13/fieldfield_path-leaked_cache_metadata-3074642-2.patch)?

**Comment by cristiroma** [comment]
Yes, the issue number is in the patch filename - https://www.drupal.org/project/filefield_paths/issues/3074642

**Comment by Hayk-web** [comment]
> Yes, the issue number is in the patch filename - https://www.drupal.org/project/filefield_paths/issues/3074642

Fine. I understood. Have you used it for resolving the early rendering issue?

**Comment by cristiroma** [comment]
I'm not sure what you're asking. Yes, I've used the debugger to catch the error according to the article I've mentioned and I saw the metadata leak comes from the `filefield_paths` module. I've checked out the issue queue and found this issue which describes the same problem.

**Comment by Hayk-web** [comment]
The issue has been fixed. It was related to the field_date, which has been created as a required field in this branch and hasn't been added to test files, which create the nodes.

**Comment by longhotsummer** [comment]
Great!

**Review by longhotsummer — APPROVED** [review]

**Comment by longhotsummer** [comment]
@roger-cts tagging you so you're aware of the change. We can then merge and test this with legislation PDFs.

**Comment by longhotsummer** [comment]
@Hayk-web does this mean we can close #189?

**Comment by Hayk-web** [comment]
@longhotsummer Yes. All works correctly with applied patches.

**Review by Hayk-web — APPROVED** [review]

**Pull request merged**
