### PR TITLE
Updated indigo-web, NA styling

### PR DESCRIPTION
**Pull request by longhotsummer**
This updates legislation styling, and includes new styling for Namibia.

### CODE REVIEW

**Comment by roger-cts** [comment]
@longhotsummer is this a Namiblii specific update or should it be rolled out to master?

**Comment by longhotsummer** [comment]
It needs to go out everywhere. The Namibia-specific styling will be applied only to Namiblii automatically.

Edit: I see that I need to make a tweak to get Namibia styling to apply automatically. Give me a few mins...

**Comment by roger-cts** [comment]
Sure thing

**Comment by longhotsummer** [comment]
image

Green is for NA only.

**Comment by longhotsummer** [comment]
@roger-cts ready for review

**Review by roger-cts — APPROVED** [review]

**Pull request merged**
