### PR TITLE
Fix filefield_paths module with a patch

### PR DESCRIPTION
**Pull request by adolflategan**
A patch for the filefield_paths module to ensure that the files are always uploaded to the temp directory before being moved by the module, because it is required by the module.

### CODE REVIEW

**Comment by longhotsummer** [comment]
Thanks @adolflategan - I note the change in PHP version from 7.3 to 7.2 -- is that deliberate? Anything we should be aware of if we're going back a version?

**Comment by adolflategan** [comment]
Hi @longhotsummer . Our servers still run 7.2 for the time being before we're upgrading later this year, but I can revert this back to 7.3 for you as the minimum requirement, however if your servers are running a higher version this shouldn't have any impact?

**Comment by longhotsummer** [comment]
@adolflategan it looks like a number of dependencies have changed, and the tests are now failing. Please can we get this with just the patch, and no changes to the dependencies or the PHP version? We don't have capacity to resolve all those issues right now.

**Comment by adolflategan** [comment]
@longhotsummer I have made the amends you requested. Let me know if you're happy with it.

**Comment by longhotsummer** [comment]
@adolflategan super, thanks!

@roger-cts do you want to merge this and either test on your machine, or we can deploy and test?

**Comment by roger-cts** [comment]
> @adolflategan super, thanks!
> 
> @roger-cts do you want to merge this and either test on your machine, or we can deploy and test?

I think we can just deploy and test

**Pull request merged**
