### PR TITLE
Judgement layout

### PR DESCRIPTION
**Pull request by stefanbutura**

### CODE REVIEW

**Comment by longhotsummer** [comment]
Thanks @stefanbutura this is looking great. I get a few errors when displaying a node, they all look related:

Mofuka vs Bank Windhoek Limited and Another (I 2508:2012)  2019  NAHCMD 200 (20 June 2019) ( number 2508 of 2012)  2019  1 (20 … 2020-06-02 12-21-52

Any ideas?

**Comment by longhotsummer** [comment]
Error text is:

Notice: Undefined index: field_judgment_date in ds_preprocess_ds_layout() (line 618 of modules/contrib/ds/ds.module).
ds_preprocess_ds_layout(Array, 'liibarrio_content_general', Array) (Line: 287)
Drupal\Core\Theme\ThemeManager->render('liibarrio_content_general', Array) (Line: 431)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 200)
Drupal\Core\Render\Renderer->render(Array) (Line: 501)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 58)
__TwigTemplate_c1b283498ca68099afccaee09222fcd22259d880a95bf97a596ca25a98b84695->doDisplay(Array, Array) (Line: 455)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 422)
Twig\Template->display(Array) (Line: 434)
Twig\Template->render(Array) (Line: 64)
twig_render_template('modules/contrib/ds/templates/ds-entity-view.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('ds_entity_view', Array) (Line: 431)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 200)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 226)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 573)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 227)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 117)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object) (Line: 76)
Drupal\webprofiler\EventDispatcher\TraceableEventDispatcher->dispatch('kernel.view', Object) (Line: 156)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 38)
Drupal\webprofiler\StackMiddleware\WebprofilerMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 694)
Drupal\Core\DrupalKernel->handle(Object)...

**Comment by stefanbutura** [comment]
> Error text is:
> 
> Notice: Undefined index: field_judgment_date in ds_preprocess_ds_layout() (line 618 of modules/contrib/ds/ds.module).
> ds_preprocess_ds_layout(Array, 'liibarrio_content_general', Array) (Line: 287)
> Drupal\Core\Theme\ThemeManager->render('liibarrio_content_general', Array) (Line: 431)
> Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 200)
> Drupal\Core\Render\Renderer->render(Array) (Line: 501)
> Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 58)
> __TwigTemplate_c1b283498ca68099afccaee09222fcd22259d880a95bf97a596ca25a98b84695->doDisplay(Array, Array) (Line: 455)
> Twig\Template->displayWithErrorHandling(Array, Array) (Line: 422)
> Twig\Template->display(Array) (Line: 434)
> Twig\Template->render(Array) (Line: 64)
> twig_render_template('modules/contrib/ds/templates/ds-entity-view.html.twig', Array) (Line: 384)
> Drupal\Core\Theme\ThemeManager->render('ds_entity_view', Array) (Line: 431)
> Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 200)
> Drupal\Core\Render\Renderer->render(Array, ) (Line: 226)
> Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent{closure}() (Line: 573)
> Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 227)
> Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 117)
> Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
> Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object) (Line: 76)
> Drupal\webprofiler\EventDispatcher\TraceableEventDispatcher->dispatch('kernel.view', Object) (Line: 156)
> Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
> Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
> Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
> Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 47)
> Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 38)
> Drupal\webprofiler\StackMiddleware\WebprofilerMiddleware->handle(Object, 1, 1) (Line: 52)
> Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
> Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 694)
> Drupal\Core\DrupalKernel->handle(Object)...

Looks like Display Suite gets a little bit confused when a region has the "content" ID. I renamed "content" to "node_content" in the last commit.

**Comment by longhotsummer** [comment]
That fixed it, thanks!

**Pull request merged**
